/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-codegen-extensions.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-codegen-extensions.yang */
public class openconfigCodegenExtensions extends ConfNamespace {
    public static final int hash = 789140070;
    public int hash() {
        return openconfigCodegenExtensions.hash;
    }

    public static final String id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openconfig-codegen-ext";
    public String id() {
        return openconfigCodegenExtensions.id;
    }

    public static final String uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openconfig-codegen-ext";
    public String uri() {
        return openconfigCodegenExtensions.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigCodegenExtensions.uri);
    }

    public static final String prefix = "oc-codegen-ext";
    public String prefix() {
        return openconfigCodegenExtensions.prefix;
    }

    public openconfigCodegenExtensions() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
