/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-fan.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-fan.yang */
public class openconfigPlatformFan extends ConfNamespace {
    public static final int hash = 1612554408;
    public int hash() {
        return openconfigPlatformFan.hash;
    }

    public static final String id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/platform/fan";
    public String id() {
        return openconfigPlatformFan.id;
    }

    public static final String uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/platform/fan";
    public String uri() {
        return openconfigPlatformFan.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformFan.uri);
    }

    public static final String prefix = "oc-fan";
    public String prefix() {
        return openconfigPlatformFan.prefix;
    }

    public openconfigPlatformFan() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _speed = 1423237997;
    public static final String _speed_ = "speed";
}
