/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-oinis-nc-ned-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-oinis-nc-ned-nc.yang */
public class tailfNedIdOinisNcNedNc extends ConfNamespace {
    public static final int hash = 91895402;
    public int hash() {
        return tailfNedIdOinisNcNedNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc";
    public String id() {
        return tailfNedIdOinisNcNedNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc";
    public String uri() {
        return tailfNedIdOinisNcNedNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOinisNcNedNc.uri);
    }

    public static final String prefix = "oinis-nc-ned-nc";
    public String prefix() {
        return tailfNedIdOinisNcNedNc.prefix;
    }

    public tailfNedIdOinisNcNedNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _oinis_nc_ned_nc = 964047454;
    public static final String _oinis_nc_ned_nc_ = "oinis-nc-ned-nc";
    public static final int    ned_id = 964047454;
    public static final String ned_id_ = "oinis-nc-ned-nc:oinis-nc-ned-nc";
}
