/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-oinis-nc-ned-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-oinis-nc-ned-nc-1.0.yang */
public class tailfNedIdOinisNcNedNc1_0 extends ConfNamespace {
    public static final int hash = 657082113;
    public int hash() {
        return tailfNedIdOinisNcNedNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc-1.0";
    public String id() {
        return tailfNedIdOinisNcNedNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc-1.0";
    public String uri() {
        return tailfNedIdOinisNcNedNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOinisNcNedNc1_0.uri);
    }

    public static final String prefix = "oinis-nc-ned-nc-1.0";
    public String prefix() {
        return tailfNedIdOinisNcNedNc1_0.prefix;
    }

    public tailfNedIdOinisNcNedNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _oinis_nc_ned_nc_10x2e0 = 1834903722;
    public static final String _oinis_nc_ned_nc_10x2e0_ = "oinis-nc-ned-nc-1.0";
}
