#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-oinis-nc-ned-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-oinis-nc-ned-nc.yang


class ns(object):
    hash = 91895402

    id = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc"

    uri = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc"

    prefix = "oinis-nc-ned-nc"

    oinis_nc_ned_nc_oinis_nc_ned_nc = 964047454
    oinis_nc_ned_nc_oinis_nc_ned_nc_ = "oinis-nc-ned-nc"
    ned_id = 964047454
    ned_id_ = "oinis-nc-ned-nc:oinis-nc-ned-nc"
