#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-oinis-nc-ned-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-oinis-nc-ned-nc-1.0.yang


class ns(object):
    hash = 657082113

    id = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/oinis-nc-ned-nc-1.0"

    prefix = "oinis-nc-ned-nc-1.0"

    oinis_nc_ned_nc_10x2e0_oinis_nc_ned_nc_10x2e0 = 1834903722
    oinis_nc_ned_nc_10x2e0_oinis_nc_ned_nc_10x2e0_ = "oinis-nc-ned-nc-1.0"
