#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-network-instance-policy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-network-instance-policy.yang


class ns(object):
    hash = 1636986811

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/network-instance/policy"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/network-instance/policy"

    prefix = "oc-ni-pol"

    oc_ni_pol_protocol_name = 684080917
    oc_ni_pol_protocol_name_ = "protocol-name"
    oc_ni_pol_protocol_identifier = 1431250581
    oc_ni_pol_protocol_identifier_ = "protocol-identifier"
    oc_ni_pol_state = 630973766
    oc_ni_pol_state_ = "state"
    oc_ni_pol_config = 2105663071
    oc_ni_pol_config_ = "config"
    oc_ni_pol_match_protocol_instance = 1433286145
    oc_ni_pol_match_protocol_instance_ = "match-protocol-instance"
