#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-segment-routing.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-segment-routing.yang


class ns(object):
    hash = 199661961

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/sr"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/sr"

    prefix = "oc-sr"

    oc_sr_NO_PHP = 0
    oc_sr_NO_PHP_ = "NO_PHP"
    oc_sr_EXPLICIT_NULL = 1
    oc_sr_EXPLICIT_NULL_ = "EXPLICIT_NULL"
