#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-openflow-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-openflow-types.yang


class ns(object):
    hash = 415808982

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openflow/types"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openflow/types"

    prefix = "openflow-types"

    openflow_types_TCP = 0
    openflow_types_TCP_ = "TCP"
    openflow_types_TLS = 1
    openflow_types_TLS_ = "TLS"
    openflow_types_SECURE = 0
    openflow_types_SECURE_ = "SECURE"
    openflow_types_STANDALONE = 1
    openflow_types_STANDALONE_ = "STANDALONE"
