#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-policy-forwarding.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-policy-forwarding.yang


class ns(object):
    hash = 988021174

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/policy-forwarding"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/policy-forwarding"

    prefix = "oc-pf"

    oc_pf_VRF_SELECTION_POLICY = 1
    oc_pf_VRF_SELECTION_POLICY_ = "VRF_SELECTION_POLICY"
    oc_pf_PBR_POLICY = 0
    oc_pf_PBR_POLICY_ = "PBR_POLICY"
