#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-fw-link-monitoring.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-fw-link-monitoring.yang


class ns(object):
    hash = 1052708300

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openconfig-fw-link-monitoring"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/openconfig-fw-link-monitoring"

    prefix = "oc-fw-linkmon"

    oc_fw_linkmon_ANY = 0
    oc_fw_linkmon_ANY_ = "ANY"
    oc_fw_linkmon_DOWN = 1
    oc_fw_linkmon_DOWN_ = "DOWN"
    oc_fw_linkmon_ALL = 1
    oc_fw_linkmon_ALL_ = "ALL"
    oc_fw_linkmon_UP = 0
    oc_fw_linkmon_UP_ = "UP"
