#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-alarms.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-alarms.yang


class ns(object):
    hash = 805894450

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/alarms"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/alarms"

    prefix = "oc-alarms"

    oc_alarms_equipment_failure = 1499913034
    oc_alarms_equipment_failure_ = "equipment-failure"
    oc_alarms_equipment_mismatch = 1812222
    oc_alarms_equipment_mismatch_ = "equipment-mismatch"
