#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-pim-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-pim-types.yang


class ns(object):
    hash = 1122256759

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/pim/types"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/pim/types"

    prefix = "oc-pim-types"

    oc_pim_types_PIM_MODE = 1303515708
    oc_pim_types_PIM_MODE_ = "PIM_MODE"
    oc_pim_types_PIM_MODE_DENSE = 77129274
    oc_pim_types_PIM_MODE_DENSE_ = "PIM_MODE_DENSE"
    oc_pim_types_PIM_MODE_SPARSE = 1344031631
    oc_pim_types_PIM_MODE_SPARSE_ = "PIM_MODE_SPARSE"
