#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-mpls-sr.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-mpls-sr.yang


class ns(object):
    hash = 319874699

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/mpls-sr"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/mpls-sr"

    prefix = "oc-mpls-sr"

    oc_mpls_sr_ADJ_SID_ONLY = 0
    oc_mpls_sr_ADJ_SID_ONLY_ = "ADJ_SID_ONLY"
    oc_mpls_sr_MIXED_MODE = 1
    oc_mpls_sr_MIXED_MODE_ = "MIXED_MODE"
