#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-p4rt.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-p4rt.yang


class ns(object):
    hash = 1972738165

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/p4rt"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/p4rt"

    prefix = "oc-p4rt"

    oc_p4rt_node_id = 98319925
    oc_p4rt_node_id_ = "node-id"
    oc_p4rt_id = 1279252765
    oc_p4rt_id_ = "id"
    oc_p4rt_P4RT = 1548290100
    oc_p4rt_P4RT_ = "P4RT"
