#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-srte-policy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-srte-policy.yang


class ns(object):
    hash = 1789754902

    id = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/segment-routing/srte-policy"

    uri = "_oinis-nc-ned-nc-1.0:oinis-nc-ned-nc-1.0#http://openconfig.net/yang/segment-routing/srte-policy"

    prefix = "oc-srte"

